name: example
description: Simple project to showcase the usage of flame_tiled
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flame: 1.0.0-releasecandidate.11
  flame_tiled:
    path: ../
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/tiles/map.tmx
    - assets/images/map-level1.png
    - assets/images/map-level2.png
    - assets/images/coins.png
